### ISSUE TITLE
A possible error in kvp_attention_cell.py

### ISSUE THREAD

**Issue by TOM-ZXian** [asahi417/LSTMCell#1]
As present in ‘’Frustratingly short attention spans in neural language modeling‘’ , i guess that
the code in LSTMCell/cells/kvp_attention_cell.py (136~146 lines)
" 
                alignments.append(cell_output)
                if len(alignments) < self._attention_window:
                    ...
                else:
                    ....
                outputs.append(output)
"

should be fixed to

"
                if len(alignments) < self._attention_window:
                    ...
                else:
                    ....
                alignments.append(cell_output)
                outputs.append(output)
"

And, with one layer of LSTM_cell, this model can get better performance.

**Comment by asahi417** [comment]
Thanks for letting me know that! I will check it and retrain that model over PTB later.
